services:
  quizDB:
    image: postgres:15.3
    container_name: quiz-db
    restart: always
    ports:
      - 5460:5432 # HOST_PORT:CONTAINER_PORT
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s